from __future__ import annotations

from pathlib import Path
from runbook_hermes import tools

TOOLSET = "runbook-observability"


def _schema(name, description, properties, required=None):
    return {"name": name, "description": description, "parameters": {"type": "object", "properties": properties, "required": required or []}}


def register(ctx):
    common_service = {"type": "string", "description": "Service name", "default": "payment-service"}
    ctx.register_tool("prom_query", TOOLSET, _schema("prom_query", "Run a Prometheus query through the configured metrics backend.", {"service": common_service, "query": {"type": "string"}, "window": {"type": "string", "default": "15m"}}, ["service"]), tools.prom_query, description="Run Prometheus query", emoji="📈")
    ctx.register_tool("prom_top_anomalies", TOOLSET, _schema("prom_top_anomalies", "Return top metric anomalies for a service, including HTTP 503, 504 and 429 rates.", {"service": common_service, "window": {"type": "string", "default": "15m"}}, ["service"]), tools.prom_top_anomalies, description="Metric anomalies", emoji="📈")
    ctx.register_tool("loki_query", TOOLSET, _schema("loki_query", "Search service logs through Loki or the configured log backend.", {"service": common_service, "query": {"type": "string"}, "start": {"type": "string"}, "end": {"type": "string"}, "limit": {"type": "integer", "default": 20}}, ["service"]), tools.loki_query, description="Log search", emoji="📜")
    ctx.register_tool("trace_search", TOOLSET, _schema("trace_search", "Search Jaeger traces for service errors or downstream latency.", {"service": common_service, "start": {"type": "string"}, "end": {"type": "string"}, "error_only": {"type": "boolean", "default": True}}, ["service"]), tools.trace_search, description="Trace search", emoji="🔎")
    ctx.register_tool("recent_deploys", TOOLSET, _schema("recent_deploys", "Return recent deploys for a service.", {"service": common_service, "since": {"type": "string", "default": "2h"}}, ["service"]), tools.recent_deploys, description="Recent deploys", emoji="🚀")
    ctx.register_tool("rollback_canary", TOOLSET, _schema("rollback_canary", "Rollback a canary deployment. Destructive when dry_run=false; approval is required.", {"service": common_service, "target_revision": {"type": "string"}, "dry_run": {"type": "boolean", "default": True}, "approval_id": {"type": "string"}, "checkpoint_id": {"type": "string"}}, ["service", "target_revision"]), tools.rollback_canary, description="Rollback canary", emoji="🛡️")
    ctx.register_tool("verify_recovery", TOOLSET, _schema("verify_recovery", "Verify whether HTTP 503 recovery signals improved after a controlled demo rollback.", {"service": common_service, "window": {"type": "string", "default": "2m"}}, ["service"]), tools.verify_recovery, description="Verify recovery", emoji="✅")
    ctx.register_tool("incident_rca_guard", TOOLSET, _schema("incident_rca_guard", "Validate or generate an RCA hypothesis from evidence.", {"service": common_service, "evidence": {"type": "array", "items": {"type": "object"}}}, ["service", "evidence"]), tools.incident_rca_guard, description="RCA guard", emoji="🧭")
    ctx.register_tool("action_policy_guard", TOOLSET, _schema("action_policy_guard", "Generate policy-checked actions from a root-cause hypothesis.", {"service": common_service, "hypothesis": {"type": "object"}}, ["service", "hypothesis"]), tools.action_policy_guard, description="Action policy", emoji="⚖️")
    ctx.register_tool("runbook_approval_decision", TOOLSET, _schema("runbook_approval_decision", "Approve or reject a pending RunbookHermes destructive action.", {"approval_id": {"type": "string"}, "decision": {"type": "string", "enum": ["approved", "rejected"]}, "approver": {"type": "string"}, "comment": {"type": "string"}}, ["approval_id", "decision"]), tools.runbook_approval_decision, description="Approval decision", emoji="✅")
    ctx.register_tool("execute_controlled_action", TOOLSET, _schema("execute_controlled_action", "Execute or route a non-rollback controlled action through the configured executor shell. Disabled by default unless ACTION_EXECUTION_BACKEND is configured.", {"service": common_service, "incident_id": {"type": "string"}, "action_type": {"type": "string"}, "title": {"type": "string"}, "risk_level": {"type": "string"}, "approval_id": {"type": "string"}, "action_args": {"type": "object"}}, ["service", "action_type"]), tools.execute_controlled_action, description="Execute controlled action", emoji="🧰")
    ctx.register_tool("runbook_memory_recall", TOOLSET, _schema("runbook_memory_recall", "Recall fenced RunbookHermes memory from notebooks, SQLite FTS5 and local HRR vectors.", {"service": common_service, "query": {"type": "string"}, "summary": {"type": "string"}, "alert_name": {"type": "string"}, "limit": {"type": "integer", "default": 6}}, []), tools.runbook_memory_recall, description="Recall runbook memory", emoji="🧠")
    ctx.register_tool("runbook_memory_write", TOOLSET, _schema("runbook_memory_write", "Write stable RunbookHermes memory after safety scanning. Use only for durable facts, governance rules, team habits or reusable incident summaries.", {"service": common_service, "kind": {"type": "string", "default": "manual_note", "enum": ["incident_summary", "fault_pattern", "team_preference", "service_governance", "service_profile", "skill_index", "manual_note", "rag_document", "visual_observation", "topology_observation"]}, "title": {"type": "string"}, "body": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}, "source": {"type": "string"}, "incident_id": {"type": "string"}, "notebook": {"type": "string", "enum": ["MEMORY.md", "USER.md", "SERVICE_PROFILE.md", "FAULT_PATTERNS.md", "TEAM_RUNBOOK_HABITS.md"]}}, ["title", "body"]), tools.runbook_memory_write, description="Write safe memory", emoji="📝")
    ctx.register_tool("runbook_memory_feedback", TOOLSET, _schema("runbook_memory_feedback", "Record operator feedback for a memory hit so trust scores can evolve.", {"memory_id": {"type": "string"}, "label": {"type": "string", "enum": ["helpful", "wrong", "stale", "harmful"]}, "comment": {"type": "string"}, "weight": {"type": "number"}}, ["memory_id", "label"]), tools.runbook_memory_feedback, description="Memory feedback", emoji="👍")
    ctx.register_tool("runbook_memory_status", TOOLSET, _schema("runbook_memory_status", "Return memory layer status, FTS5/HRR capacity and external provider mode.", {}, []), tools.runbook_memory_status, description="Memory status", emoji="📊")
    ctx.register_tool("runbook_evolution_digest", TOOLSET, _schema("runbook_evolution_digest", "Summarize learned fault patterns, team preferences and runbook promotion suggestions.", {"limit": {"type": "integer", "default": 8}}, []), tools.runbook_evolution_digest, description="Evolution digest", emoji="🌱")
    ctx.register_tool("runbook_memory_reindex_skills", TOOLSET, _schema("runbook_memory_reindex_skills", "Index local SKILL.md files and generated runbook skills into RunbookHermes memory.", {}, []), tools.runbook_memory_reindex_skills, description="Index runbook skills", emoji="📚")
    ctx.register_tool("runbook_memory_route", TOOLSET, _schema("runbook_memory_route", "Classify a chat/Feishu message and route it to Hermes native memory, RunbookHermes domain memory, recall, skill publishing or incident creation.", {"message": {"type": "string"}, "source": {"type": "string", "default": "chat"}, "metadata": {"type": "object"}, "apply": {"type": "boolean", "default": False}}, ["message"]), tools.runbook_memory_route, description="Route memory", emoji="🧭")
    ctx.register_tool("runbook_publish_skill", TOOLSET, _schema("runbook_publish_skill", "Publish generated runbook content into Hermes official Skills directory.", {"service": common_service, "incident_id": {"type": "string"}, "skill_id": {"type": "string"}, "title": {"type": "string"}, "body": {"type": "string"}}, ["title", "body"]), tools.runbook_publish_skill, description="Publish runbook skill", emoji="📦")
    ctx.register_tool("runbook_skill_publish_status", TOOLSET, _schema("runbook_skill_publish_status", "Return Hermes official Skills publisher status for RunbookHermes.", {}, []), tools.runbook_skill_publish_status, description="Skill publisher", emoji="📚")

    ctx.register_tool("runbook_rag_status", TOOLSET, _schema("runbook_rag_status", "Return RunbookHermes local citation RAG index status.", {}, []), tools.runbook_rag_status, description="RAG status", emoji="📚")
    ctx.register_tool("runbook_rag_ingest_text", TOOLSET, _schema("runbook_rag_ingest_text", "Ingest a text/markdown/SRE document into the local citation RAG index.", {"service": common_service, "title": {"type": "string"}, "body": {"type": "string"}, "source": {"type": "string", "default": "tool"}, "tags": {"type": "array", "items": {"type": "string"}}, "metadata": {"type": "object"}}, ["title", "body"]), tools.runbook_rag_ingest_text, description="Ingest RAG doc", emoji="📥")
    ctx.register_tool("runbook_rag_search", TOOLSET, _schema("runbook_rag_search", "Search the RunbookHermes knowledge base and return source/chunk citations.", {"service": common_service, "query": {"type": "string"}, "limit": {"type": "integer", "default": 5}, "include_text": {"type": "boolean", "default": False}}, ["query"]), tools.runbook_rag_search, description="Search RAG", emoji="🔎")
    ctx.register_tool("runbook_rag_context", TOOLSET, _schema("runbook_rag_context", "Build a fenced RAG context block for RCA and action planning.", {"service": common_service, "query": {"type": "string"}, "limit": {"type": "integer", "default": 5}}, ["query"]), tools.runbook_rag_context, description="RAG context", emoji="🧱")
    ctx.register_tool("runbook_multimodal_analyze", TOOLSET, _schema("runbook_multimodal_analyze", "Analyze Grafana screenshots, Feishu alert cards, topology diagrams, log screenshots and dashboard images into AIOps evidence.", {"service": common_service, "summary": {"type": "string"}, "incident_id": {"type": "string"}, "visual_refs": {"type": "array", "items": {"type": "object"}}, "include_dashboard_snapshot": {"type": "boolean"}}, []), tools.runbook_multimodal_analyze, description="Analyze visual evidence", emoji="🖼️")
    ctx.register_tool("runbook_topology_parse", TOOLSET, _schema("runbook_topology_parse", "Parse topology diagram OCR/text into dependency nodes and edges.", {"service": common_service, "text": {"type": "string"}}, ["text"]), tools.runbook_topology_parse, description="Parse topology", emoji="🕸️")
    ctx.register_tool("runbook_eval_benchmark", TOOLSET, _schema("runbook_eval_benchmark", "Run deterministic RunbookHermes benchmark/eval cases for RCA, action and safety gates.", {"case_ids": {"type": "array", "items": {"type": "string"}}, "persist": {"type": "boolean", "default": False}, "model_assist": {"type": "boolean", "default": False}}, []), tools.runbook_eval_benchmark, description="Run benchmark", emoji="🧪")
    ctx.register_tool("runbook_training_status", TOOLSET, _schema("runbook_training_status", "Return RunbookAIOps training, RL and AutoPipeline status plus Hermes RL handoff availability.", {}, []), tools.runbook_training_status, description="Training status", emoji="🎓")
    ctx.register_tool("runbook_training_build_dataset", TOOLSET, _schema("runbook_training_build_dataset", "Build Hermes-compatible trajectories plus SFT, preference and reward datasets from incidents and benchmark cases.", {"include_incidents": {"type": "boolean", "default": True}, "include_benchmark_cases": {"type": "boolean", "default": True}, "max_incidents": {"type": "integer"}, "min_reward": {"type": "number"}}, []), tools.runbook_training_build_dataset, description="Build training data", emoji="🧬")
    ctx.register_tool("runbook_training_compress", TOOLSET, _schema("runbook_training_compress", "Compress RunbookAIOps trajectories or hand off to Hermes trajectory_compressor.", {"run_id": {"type": "string"}, "max_message_chars": {"type": "integer"}, "use_hermes_compressor": {"type": "boolean", "default": False}}, []), tools.runbook_training_compress, description="Compress trajectories", emoji="🗜️")
    ctx.register_tool("runbook_training_export", TOOLSET, _schema("runbook_training_export", "Export datasets and generate Alibaba Cloud PAI/DashScope dry-run handoff templates.", {"run_id": {"type": "string"}, "base_model": {"type": "string"}, "output_model_name": {"type": "string"}}, []), tools.runbook_training_export, description="Export training data", emoji="☁️")
    ctx.register_tool("runbook_training_pipeline", TOOLSET, _schema("runbook_training_pipeline", "Run the RunbookAIOps dataset -> compression -> export AutoPipeline. External launch remains dry-run unless explicitly enabled.", {"include_incidents": {"type": "boolean", "default": True}, "include_benchmark_cases": {"type": "boolean", "default": True}, "max_incidents": {"type": "integer"}, "min_reward": {"type": "number"}, "base_model": {"type": "string"}, "output_model_name": {"type": "string"}, "use_hermes_compressor": {"type": "boolean", "default": False}, "dry_run": {"type": "boolean", "default": True}}, []), tools.runbook_training_pipeline, description="Run AutoPipeline", emoji="🚂")
    skill = Path(__file__).resolve().parents[2] / "skills" / "runbooks" / "payment-503-spike" / "SKILL.md"
    if skill.exists():
        ctx.register_skill("payment-503-spike", skill, "Payment service HTTP 503 spike after release triage runbook")
